# Generated by Django 5.1.3 on 2024-11-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pipeline_CICD', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipeline',
            name='created_at',
        ),
        migrations.AddField(
            model_name='pipeline',
            name='last_run',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('RUNNING', 'Running')], default='RUNNING', max_length=50),
        ),
    ]
