name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main  # Exécuter le pipeline à chaque push sur la branche 'main'
  pull_request:
    branches:
      - main  # Exécuter le pipeline lors des pull requests vers la branche 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python manage.py test

    - name: Build Docker image
      run: |
        docker build -t todo-app .

    - name: Push Docker image to Docker Hub (optional)
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker tag todo-app:latest $DOCKER_USERNAME/todo-app:latest
        docker push $DOCKER_USERNAME/todo-app:latest

    - name: Deploy to server (example for Heroku)
      run: |
        git remote add heroku https://git.heroku.com/$HEROKU_APP_NAME.git
        git push heroku main
